services:
  # client-react-vite:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   init: true
  #   volumes:
  #     - type: bind
  #       source: .
  #       target: /usr/src/app/
  #     - type: volume
  #       target: /usr/src/app/node_modules 
  #     - type: bind
  #       source: vite.config.js
  #       target: /usr/src/app/vite.config.js
  #   networks:
  #     - frontend
  #   ports:
  #     - 5173:5173
  client-react-nginx:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped

networks:
  frontend:
    driver: bridge